### ISSUE TITLE
226 is an unsupported value for <enum 'MeasurementType'>

### ISSUE THREAD

**Issue by Chili-Bang-Bang** [joostlek/python-withings#157]
# Problem/Motivation

> @joostlek found bug in my Logs

## Expected behavior

> correct Value

## Actual behavior

> unsupported value

## Steps to reproduce

> Not sure :)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

Report of this issue.

Devices i use:

Withings Stee HR Watch
Withings Body+ Scale

Not sure witch one of the Devices causes the issue.

**Comment by joostlek** [comment]
Thanks, this will also go on my list of stuff I need to look after at the Withings website

**Comment by askthomas** [comment]
2024-02-10 23:08:11.137 WARNING (MainThread) [aiowithings] 10 is an unsupported value for <enum 'MeasurementAttribution'>, please report this at https://github.com/joostlek/python-withings/issues

Scale: Body Cardio, FW 2018 Sep 22. Version  1721

**Comment by atrepca** [comment]
Seeing the same issue in the logs here, glad to help debug if needed.

**Comment by Hooch76** [comment]
+1
```
WARNING (MainThread) [aiowithings] 226 is an unsupported value for <enum 'MeasurementType'>, please report this at https://github.com/joostlek/python-withings/issues
```

**Comment by thierryzoller** [comment]
+1

**Comment by hundehausen** [comment]
+1

**Comment by joostlek** [comment]
Finally found some time to send an email to Withings. Will follow up.

**Comment by SeanPM5** [comment]
Saw this today in my logs for the first time, after getting a new "Body Smart" scale. Never had issues with the sleep mat, also added the Withings BPM Connect a few days ago and didn't notice it there either, seems scale specific. 

Dunno if any of this info helps narrow things down, but...
- I enabled the "Hydration" sensor, everything else was default entities
- Changed unit of measurement for the body composition sensors (through entity more info dialog) from `kg` to `lb`
- Scale is shared with another family member (separate Withings account, not a profile) and their data is in HA
- Scale firmware version 1071

**Comment by anthonym21** [comment]
226 is BASAL_METABOLIC_RATE and is a calculated field provided by the Body Scan scale along with some of the fitness tracker watches, it should be as easy to fix as the others, my PR changes fixed it locally. Note it will come in with position: 7 (whole body)
Example:
[...,...
          {
            "value": 2252,
            "type": 226,
            "unit": 0,
            "algo": 218235904,
            "fm": 131,
            "position": 7
          }
        ],
        "modelid": 10,
        "model": "Body Scan",
        "comment": null
      }

2252 kcal is the value here with unit

**Comment by joostlek** [comment]
How did you find that out?

**Comment by anthonym21** [comment]
I have a body scan, so I measured myself and then I hit their API and got everything back that comes in the measure call including all the new metrics.

Then I painstakingly checked each unknown measurement type against my own known metric values in the Withings app to find which obscure value matched what I had in my mystery metric. In case of it being ambiguous, I took additional measurements or measured my daughter.

 It takes a minute to see the correlations  due to rounding errors, not necessarily knowing the units, and the lack of decimal points but its not anything crazy.  The _really_ hard ones luckily are in their developer documentation which I'm sure you're aware of.

https://developer.withings.com/api-reference#tag/measure/operation/measure-getmeas

Also "7" for full body measurements is not in their api reference for some reason but it was obvious looking at real data.

**Comment by anthonym21** [comment]
Also if you login to the Withings dashboard and throw Chrome in developer mode you can get some of the missing enum value type names in their javascript (but expect to dig through obscufated code) and then observe the XHR requests and responses and you can get the same data as you would from the API without having to bother with the API.
